using MasterDevs.ChromeDevTools;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace MasterDevs.ChromeDevTools.Protocol.Chrome.Network
{
	/// <summary>
	/// Enables tracking for the Reporting API, events generated by the Reporting API will now be delivered to the client.
	/// Enabling triggers 'reportingApiReportAdded' for all existing reports.
	/// </summary>
	[Command(ProtocolName.Network.EnableReportingApi)]
	[SupportedBy("Chrome")]
	public class EnableReportingApiCommand: ICommand<EnableReportingApiCommandResponse>
	{
		/// <summary>
		/// Gets or sets Whether to enable or disable events for the Reporting API
		/// </summary>
		public bool Enable { get; set; }
	}
}
